
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adarsh
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    Color DefaultColor,ClickedColor;
            
    public Dashboard() {
        initComponents();
        DefaultColor=new Color(153,102,255);
        ClickedColor=new Color(255,255,102);
        
        //set default color to pan on run time
        RequestPickup.setBackground(DefaultColor);
        MyOrders.setBackground(DefaultColor);
        RateCalc.setBackground(DefaultColor);
        InvoicePrinting.setBackground(DefaultColor);
        Back.setBackground(DefaultColor);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuName = new javax.swing.JLabel();
        MenuDetails = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RequestPickup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MyOrders = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RateCalc = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        InvoicePrinting = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Back = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("IndCold Logistics");

        MenuName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        MenuName.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh\\Downloads\\iconfinder_list-mark-sign-option-menu_3643763.png")); // NOI18N
        MenuName.setText("Category");

        MenuDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MenuDetails.setText("Category Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(MenuDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(MenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(MenuName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        RequestPickup.setBackground(new java.awt.Color(153, 102, 255));
        RequestPickup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RequestPickupMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RequestPickupMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh\\Downloads\\iconfinder_package_3325012.png")); // NOI18N
        jLabel1.setText("Request Pickup");

        javax.swing.GroupLayout RequestPickupLayout = new javax.swing.GroupLayout(RequestPickup);
        RequestPickup.setLayout(RequestPickupLayout);
        RequestPickupLayout.setHorizontalGroup(
            RequestPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestPickupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RequestPickupLayout.setVerticalGroup(
            RequestPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        MyOrders.setBackground(new java.awt.Color(153, 102, 255));
        MyOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOrdersMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MyOrdersMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh\\Downloads\\iconfinder_notepad_1291737.png")); // NOI18N
        jLabel5.setText("  My Orders");

        javax.swing.GroupLayout MyOrdersLayout = new javax.swing.GroupLayout(MyOrders);
        MyOrders.setLayout(MyOrdersLayout);
        MyOrdersLayout.setHorizontalGroup(
            MyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MyOrdersLayout.setVerticalGroup(
            MyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        RateCalc.setBackground(new java.awt.Color(153, 102, 255));
        RateCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RateCalcMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RateCalcMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh\\Downloads\\iconfinder_calculator_4635001.png")); // NOI18N
        jLabel6.setText(" Rate Calculator");

        javax.swing.GroupLayout RateCalcLayout = new javax.swing.GroupLayout(RateCalc);
        RateCalc.setLayout(RateCalcLayout);
        RateCalcLayout.setHorizontalGroup(
            RateCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RateCalcLayout.setVerticalGroup(
            RateCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        InvoicePrinting.setBackground(new java.awt.Color(153, 102, 255));
        InvoicePrinting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoicePrintingMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InvoicePrintingMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh\\Downloads\\iconfinder_multimedia-30_2849806.png")); // NOI18N
        jLabel7.setText("Invoice Printing");

        javax.swing.GroupLayout InvoicePrintingLayout = new javax.swing.GroupLayout(InvoicePrinting);
        InvoicePrinting.setLayout(InvoicePrintingLayout);
        InvoicePrintingLayout.setHorizontalGroup(
            InvoicePrintingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePrintingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        InvoicePrintingLayout.setVerticalGroup(
            InvoicePrintingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        Back.setBackground(new java.awt.Color(153, 102, 255));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh\\Downloads\\iconfinder_point-left-arrow-curve-back_3209442.png")); // NOI18N
        jLabel8.setText("Back to Home");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RequestPickup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MyOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RateCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InvoicePrinting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(RequestPickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MyOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RateCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InvoicePrinting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void RequestPickupMousePressed(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        RequestPickup.setBackground(ClickedColor);
        MyOrders.setBackground(DefaultColor);
        RateCalc.setBackground(DefaultColor);
        InvoicePrinting.setBackground(DefaultColor);
        Back.setBackground(DefaultColor);
        
        MenuName.setText("Request Pickup");
        MenuDetails.setText("Request Pickup From Home");
    }                                          

    private void MyOrdersMousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        RequestPickup.setBackground(DefaultColor);
        MyOrders.setBackground(ClickedColor);
        RateCalc.setBackground(DefaultColor);
        InvoicePrinting.setBackground(DefaultColor);
        Back.setBackground(DefaultColor);
        
        MenuName.setText("My Orders");
        MenuDetails.setText("Show requested Pickups");
    }                                     

    private void RateCalcMousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        RequestPickup.setBackground(DefaultColor);
        MyOrders.setBackground(DefaultColor);
        RateCalc.setBackground(ClickedColor);
        InvoicePrinting.setBackground(DefaultColor);
        Back.setBackground(DefaultColor);
        
        MenuName.setText("Rate Calculator");
        MenuDetails.setText("Calculate Rate For a pickup");
    }                                     

    private void InvoicePrintingMousePressed(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        RequestPickup.setBackground(DefaultColor);
        MyOrders.setBackground(DefaultColor);
        RateCalc.setBackground(DefaultColor);
        InvoicePrinting.setBackground(ClickedColor);
        Back.setBackground(DefaultColor);
        
        MenuName.setText("Invoice Prinitng");
        MenuDetails.setText("Print Invoice for a pickup");
    }                                            

    private void BackMousePressed(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        RequestPickup.setBackground(DefaultColor);
        MyOrders.setBackground(DefaultColor);
        RateCalc.setBackground(DefaultColor);
        InvoicePrinting.setBackground(DefaultColor);
        Back.setBackground(ClickedColor);
    }                                 

    private void RequestPickupMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        Requestpickup requestpickup=new Requestpickup();
        jDesktopPane.removeAll();
        jDesktopPane.add(requestpickup).setVisible(true);
        
    }                                          

    private void MyOrdersMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Myorders myorders=new Myorders();
        jDesktopPane.removeAll();
        jDesktopPane.add(myorders).setVisible(true);
        
    }                                     

    private void RateCalcMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Ratecalculator ratecalc=new Ratecalculator();
        jDesktopPane.removeAll();
        jDesktopPane.add(ratecalc).setVisible(true);
        
    }                                     

    private void InvoicePrintingMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        Invoiceprinting invoiceprint=new Invoiceprinting();
        jDesktopPane.removeAll();
        jDesktopPane.add(invoiceprint).setVisible(true);
    }                                            

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.show();
        dispose();
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Back;
    private javax.swing.JPanel InvoicePrinting;
    private javax.swing.JLabel MenuDetails;
    private javax.swing.JLabel MenuName;
    private javax.swing.JPanel MyOrders;
    private javax.swing.JPanel RateCalc;
    private javax.swing.JPanel RequestPickup;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration                   
}
